package com.example.samsung.a5_30zuoye2.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.samsung.a5_30zuoye2.bean.ShuJu;

import com.example.samsung.a5_30zuoye2.dao.ShuJuDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig shuJuDaoConfig;

    private final ShuJuDao shuJuDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        shuJuDaoConfig = daoConfigMap.get(ShuJuDao.class).clone();
        shuJuDaoConfig.initIdentityScope(type);

        shuJuDao = new ShuJuDao(shuJuDaoConfig, this);

        registerDao(ShuJu.class, shuJuDao);
    }
    
    public void clear() {
        shuJuDaoConfig.clearIdentityScope();
    }

    public ShuJuDao getShuJuDao() {
        return shuJuDao;
    }

}
