package com.example.samsung.xiaoshixunqizhong.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.samsung.xiaoshixunqizhong.bean.Home;

import com.example.samsung.xiaoshixunqizhong.dao.HomeDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig homeDaoConfig;

    private final HomeDao homeDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        homeDaoConfig = daoConfigMap.get(HomeDao.class).clone();
        homeDaoConfig.initIdentityScope(type);

        homeDao = new HomeDao(homeDaoConfig, this);

        registerDao(Home.class, homeDao);
    }
    
    public void clear() {
        homeDaoConfig.clearIdentityScope();
    }

    public HomeDao getHomeDao() {
        return homeDao;
    }

}
